In [10]:
import pandas as pd
df = pd.read_csv('tip.csv')

In [11]:
df.head ()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
df.shape

(244, 7)

In [14]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [15]:
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [16]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [40]:
df[['total_bill','tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [18]:
df.iloc[0:10]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [19]:
df.iloc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [43]:
dinner_bill=df[df['total_bill']>20]
print (len(dinner_bill))
print (dinner_bill.head())

97
   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [44]:
female_visitor=df[df['sex']=='Female']
print (len(female_visitor))
print (female_visitor.head())

87
    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [45]:
dinner_time=df[df['time']=='Dinner']
print (len(dinner_time))
print (dinner_time.head())

176
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [46]:
exp_dinner=df[(df['time']=='Dinner') & (df['total_bill']>30)]
print (len(exp_dinner))
print (exp_dinner.head())

27
    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [50]:
df['total_bill'].mean()

np.float64(19.78594262295082)

In [51]:
df['tip'].max()

np.float64(10.0)

In [55]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [60]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [62]:
df.groupby('sex')['total_bill'].mean()

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [63]:
df.groupby('day')['tip'].mean()

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [66]:
df.groupby('day')['size'].mean()

day
Fri     2.105263
Sat     2.517241
Sun     2.842105
Thur    2.451613
Name: size, dtype: float64

In [76]:
df['tip_percentage']=df['tip']/df['total_bill']*100
df['tip_percentage'].head(10)

0     5.944673
1    16.054159
2    16.658734
3    13.978041
4    14.680765
5    18.623962
6    22.805017
7    11.607143
8    13.031915
9    21.853857
Name: tip_percentage, dtype: float64

In [85]:
df.sort_values('total_bill', ascending=True)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1       32.573290
92         5.75   1.00  Female    Yes   Fri  Dinner     2       17.391304
111        7.25   1.00  Female     No   Sat  Dinner     1       13.793103
172        7.25   5.15    Male    Yes   Sun  Dinner     2       71.034483
149        7.51   2.00    Male     No  Thur   Lunch     2       26.631158
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3        7.717751
156       48.17   5.00    Male     No   Sun  Dinner     6       10.379905
59        48.27   6.73    Male     No   Sat  Dinner     4       13.942407
212       48.33   9.00    Male     No   Sat  Dinner     4       18.621974
170       50.81  10.00    Male    Yes   Sat  Dinner     3       19.681165

[244 rows x 8 columns]

In [89]:
df.sort_values('tip', ascending=False)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00    Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58    Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73    Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70    Male     No  Thur   Lunch     6       19.533528
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2        5.944673
111        7.25   1.00  Female     No   Sat  Dinner     1       13.793103
92         5.75   1.00  Female    Yes   Fri  Dinner     2       17.391304
67         3.07   1.00  Female    Yes   Sat  Dinner     1       32.573290
236       12.60   1.00    Male    Yes   Sat  Dinner     2        7.936508

[244 rows x 8 columns]

In [91]:
df.nlargest(5,'tip')

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6       19.533528